# Generated by Django 4.1.2 on 2022-10-27 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user1', models.IntegerField()),
                ('user2', models.IntegerField()),
                ('cost', models.BigIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField(auto_now_add=True)),
                ('payment_status', models.CharField(choices=[('C', 'Complete'), ('P', 'Pending')], default='P', max_length=1)),
            ],
        ),
    ]
